
version: 2.1
jobs:
  test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: install dependencies
          command: pip install -r requirements.txt
      - run:
          name: run tests
          command: pytest scikit_learn/tests
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Install build tools
          command: |
            python -m pip install --upgrade pip setuptools wheel
      - run:
          name: Build the package
          command: |
            python setup.py sdist bdist_wheel
      - store_artifacts:
          path: dist/
  deploy:

workflows:
  example:
    jobs:
      - test
      - build
